import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header/Header";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { getServerSession } from "next-auth";
import MiniDrawer from "@/components/home/AsideBar";

import SessionProvider from "../components/SessioinProvider";
import NavMenu from "../components/NavbarMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html data-color-scheme="light" lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <main>
              <MiniDrawer />
              {/* <NavMenu /> */}
              {children}
            </main>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
